export const sampleNews = [
	{
		id: "368343",
		title: "Mexico Current Account Surplus Widens in Q4",
		date: "2023-02-24T15:10:22.803",
		description:
			"Mexico's current account surplus rose to USD 4,576 million in the fourth quarter of 2022, from USD 1,137 million in the corresponding quarter of the previous year, almost in line with market estimates of USD 4,400 million. The goods shortfall narrowed to USD 1,168 million from USD 2,261 million in the fourth quarter of 2021, and the services deficit declined to USD 3,119 million from USD 3,491 million. Meanwhile, the primary income gap narrowed to USD 6,526 million from USD 7,268 million, whereas the secondary income surplus rose to USD 15,390 million from USD 14,157 million. For 2022, Mexico's current account deficit widened sharply to 13,423 million from 8,209 million in 2021.",
		country: "Mexico",
		category: "Current Account",
		symbol: "OEMXB039",
		url: "/mexico/current-account",
		importance: 1,
	},
	{
		id: "368321",
		title: "Mexico Economic Activity Slows Further",
		date: "2023-02-24T13:14:24.8",
		description:
			"Economic activity in Mexico increased by 2.6 percent year-on-year in December of 2022, the slowest growth rate since July and missing estimates of a 2.8 percent expansion while easing from the upwardly revised 3.4 percent rise in the previous month. Output advanced at a slower pace for services (2.1 percent vs 3.1 percent in November) and manufacturing (3 percent vs 3.5 percent), offsetting the pickup in agriculture (8 percent vs 7.1 percent). On a seasonally adjusted monthly basis, economic activity rose by 0.3 percent in the period, rebounding from the 0.4 percent contraction in November.",
		country: "Mexico",
		category: "Monthly GDP YoY",
		symbol: "MEXMGY",
		url: "/mexico/monthly-gdp-yoy",
		importance: 1,
	},
	{
		id: "368314",
		title: "Mexico Economic Grows 3.6% in Q4",
		date: "2023-02-24T12:12:22.593",
		description:
			"Mexico’s gross domestic product expanded 3.6 percent from a year earlier in the fourth quarter of 2022, slightly above preliminary estimates of a 0.4 percent gain and easing from a revised 4.4 percent increase in the previous period. Output grew at a faster pace in the primary sector (6.3 percent vs. 3.3 percent in Q3) while slowing for manufacturing (3.2 percent vs. 3.5 percent) and services (3.5 percent vs. 4.7 percent). The Mexican economy rose by 0.5 percent quarterly, following a revised 0.9 percent gain in the previous quarter. In 2022, growth reached 3.1 percent, also slowing down from the 5 percent advance recorded in 2021.",
		country: "Mexico",
		category: "GDP Annual Growth Rate",
		symbol: "MXGCTOT",
		url: "/mexico/gdp-growth-annual",
		importance: 0,
	},
	{
		id: "368313",
		title: "Mexico Q4 GDP Growth Revised Higher",
		date: "2023-02-24T12:07:00",
		description:
			"The Mexican economy expanded 0.5 percent on quarter in the three months to December 2022, slightly above preliminary estimates of a 0.4 percent gain and easing from a revised 0.9 percent growth in the previous period. Output slowed for all three major sectors, including the primary (2.0 percent vs. 3.2 percent in Q3), manufacturing (0.5 percent vs. 0.6 percent), and services (0.1 percent vs. 1.0 percent). The country's economy advanced 3.6 percent yearly, following a revised 4.4 percent gain in the previous period but above a preliminary reading of a 4.3 percent raise. The Mexican economy expanded by 3.1 percent in 2022, slowing down from the 5 percent advance recorded last year.",
		country: "Mexico",
		category: "GDP Growth Rate",
		symbol: "MXGPQTR",
		url: "/mexico/gdp-growth",
		importance: 1,
	},
	{
		id: "368023",
		title: "Mexican Retail Sales Grows Less than Expected",
		date: "2023-02-21T12:12:18.383",
		description:
			"Retail sales in Mexico rose by 2.5 percent from a year ago in December of 2022, picking up slightly from the 2.4 percent increase in the previous month but missing market expectations of a 3.2 percent growth rate. Sharp increases were noted for paper products and textiles, while slimmer gains were reported for automobile-related stores and healthcare goods. On a seasonally adjusted monthly bases, Mexican retail sales edged 0.1 percent higher in the period, rebounding from the 0.2 percent contraction in November.",
		country: "Mexico",
		category: "Retail Sales YoY",
		symbol: "MEXRetailSalesYoY",
		url: "/mexico/retail-sales-annual",
		importance: 1,
	},
	{
		id: "367283",
		title: "Mexico Industrial Output Growth Above Forecasts",
		date: "2023-02-10T12:09:00",
		description:
			"Mexico’s industrial production rose by 3.2% from a year earlier in December 2022, following an upwardly revised 3.5% increase in the prior month and beating market forecasts of a 2% advance. It marks the 14th straight month of growth in industrial activity, mainly boosted by construction (5.5% vs 3% in November). Other positive contributions came from manufacturing (2.7% vs 4.7%); utilities (2% vs 5.1%) and mining (0.9% vs -0.5%). On a seasonally adjusted monthly basis, industrial output was up 0.7% in December, the most in a year and well above market estimates of a 0.1% rise. Considering the 2022 year as a whole, the country's industrial output grew 3.3% over a year ago.",
		country: "Mexico",
		category: "Industrial Production",
		symbol: "MXIPTYOY",
		url: "/mexico/industrial-production",
		importance: 1,
	},
	{
		id: "367184",
		title: "Banxico Unexpectedly Raises Key Rate by 50 bps to 11%",
		date: "2023-02-09T19:20:00",
		description:
			'The Bank of Mexico raised its benchmark policy rate by 50bps to 11% at its February 2023 meeting, above expectations of 25bps hike, bringing borrowing costs to their highest on record. Five of the six members of governing board unanimously voted to hike the benchmark due to "a still complex inflation environment." It was the 14th consecutive rate hike and added to the 700bps of rate increases since the start of the bank’s tightening cycle in June. The bank stated that the economy continued growing during the 4th quarter but lost its momentum compared to previous quarters, while inflation expectations for 2023 and 2024 were revised upward again. The decision came after data showed that consumer prices in January rose above December readings and market expectations.',
		country: "Mexico",
		category: "Interest Rate",
		symbol: "MXONBR",
		url: "/mexico/interest-rate",
		importance: 1,
	},
	{
		id: "367142",
		title: "Mexico Inflation Rate Speeds Up in January, Tops Forecasts",
		date: "2023-02-09T12:06:00",
		description:
			"Mexico’s annual inflation rate accelerated for the second straight month to 7.91% in January 2023, up from 7.82% in the prior month and above market expectations of 7.89%. Main upward pressure continued to come from prices of food & non-alcoholic beverages (12.77% vs 12.70% in December), mostly fruit and vegetables (10.17% vs 7.22%). Strong inflationary pressures also stemmed from restaurants & hotels (12.32% vs 12.3%); miscellaneous goods & services (10.14% vs 10.40%); alcoholic beverages & tobacco (9.53% vs 9.02%) and furnishings & household equipment (8.55% vs 8.21%). The annual core inflation rate edged up to 8.45% in January 2023, from 8.35% in the prior month, above market estimates of 8.41%. On a monthly basis, consumer prices rose by 0.68% in January, the most in five months and slightly above market estimates of a 0.64% increase. The Mexican government launched in January its third package of measures to contain the inflationary trend in staple foods.",
		country: "Mexico",
		category: "Inflation Rate",
		symbol: "MXCPYOY",
		url: "/mexico/inflation-cpi",
		importance: 1,
	},
	{
		id: "366908",
		title: "Mexico Auto Exports Grows for 2nd Month",
		date: "2023-02-07T12:45:34.683",
		description:
			"Mexico’s auto exports soared by 9.9% from a year earlier to 238,135 units in January 2023, the highest amount for the month since 2020. It marks the second straight month of increases in auto exports. Among major export brands, shipments increased from General Motors (+5% to 52,816), Stellantis (+45% to 39,123), Toyota (+27% to 23,956), Ford Motor (+37.1% to 23,937) and Audi (+67.9% to 14,884).",
		country: "Mexico",
		category: "Auto Exports",
		symbol: "MEXICOAUTEXP",
		url: "/mexico/auto-exports",
		importance: 1,
	},
	{
		id: "366901",
		title: "Mexico Car Output Rises for 9th Month",
		date: "2023-02-07T12:33:57.377",
		description:
			"Mexico’s car production rose 2.4% from a year earlier to 280,315 units in January 2023, the ninth consecutive month of increases. Among major automakers, higher output was registered for Nissan (+22.8% to 45,237), Stellantis (+70.8% to 36,900), Toyota (+11.6% to 23,703) and Mazda (+41.4% to 18,908). Conversely, decreases were mostly seen for General Motors (-11.5% to 56,182), Ford Motor (-22.4% to 22,140), KIA (-7.3% to 22,700) and Audi (-9.3% to 15,842).",
		country: "Mexico",
		category: "Car Production",
		symbol: "MEXICOCARPRO",
		url: "/mexico/car-production",
		importance: 1,
	},
	{
		id: "",
		title: "",
		date: null,
		description: "",
		country:
			"Free accounts have access to the following countries: Mexico, New Zealand, Sweden, Thailand. For more, contact us at support@tradingeconomics.com.",
		category: "",
		symbol: "",
		url: "",
		importance: 0,
	},
];
