export const sampleCal = [
	{
		CalendarId: "317360",
		Date: "2023-02-27T12:00:00",
		Country: "Mexico",
		Category: "Balance of Trade",
		Event: "Balance of Trade",
		Reference: "Jan",
		ReferenceDate: "2023-01-31T00:00:00",
		Source: "Instituto Nacional de Estadística y Geografía (INEGI)",
		SourceURL: "https://www.inegi.org.mx/",
		Actual: "",
		Previous: "$0.984B",
		Forecast: "",
		TEForecast: "$ -3.55B",
		URL: "/mexico/balance-of-trade",
		DateSpan: "0",
		Importance: 2,
		LastUpdate: "2023-01-27T12:10:13.493",
		Revised: "",
		Currency: "$",
		Unit: "B",
		Ticker: "MXTBBAL",
		Symbol: "MXTBBAL",
	},
	{
		CalendarId: "316237",
		Date: "2023-02-28T19:00:00",
		Country: "Mexico",
		Category: "Government Budget Value",
		Event: "Fiscal Balance",
		Reference: "Dec",
		ReferenceDate: "2022-12-31T00:00:00",
		Source: "Secretaría de Hacienda Y Crédito Público",
		SourceURL: "https://www.gob.mx/shcp",
		Actual: "",
		Previous: "MXN-154.83B",
		Forecast: "",
		TEForecast: "MXN -413.7B",
		URL: "/mexico/government-budget-value",
		DateSpan: "1",
		Importance: 1,
		LastUpdate: "2023-02-20T20:45:15.847",
		Revised: "",
		Currency: "MXN",
		Unit: "B",
		Ticker: "MEXICOGOVBUDVAL",
		Symbol: "MEXICOGOVBUDVAL",
	},
	{
		CalendarId: "317744",
		Date: "2023-02-28T19:00:00",
		Country: "Mexico",
		Category: "Government Budget Value",
		Event: "Fiscal Balance",
		Reference: "Jan",
		ReferenceDate: "2023-01-31T00:00:00",
		Source: "Secretaría de Hacienda Y Crédito Público",
		SourceURL: "https://www.gob.mx/shcp",
		Actual: "",
		Previous: "",
		Forecast: "",
		TEForecast: "MXN -91.8B",
		URL: "/mexico/government-budget-value",
		DateSpan: "1",
		Importance: 1,
		LastUpdate: "2023-02-24T12:54:56.87",
		Revised: "",
		Currency: "",
		Unit: "",
		Ticker: "MEXICOGOVBUDVAL",
		Symbol: "MEXICOGOVBUDVAL",
	},
	{
		CalendarId: "317644",
		Date: "2023-03-01T12:00:00",
		Country: "Mexico",
		Category: "Business Confidence",
		Event: "Business Confidence",
		Reference: "Feb",
		ReferenceDate: "2023-02-28T00:00:00",
		Source: "Instituto Nacional de Estadística y Geografía (INEGI)",
		SourceURL: "http://en.www.inegi.org.mx/",
		Actual: "",
		Previous: "49.8",
		Forecast: "",
		TEForecast: "50",
		URL: "/mexico/business-confidence",
		DateSpan: "0",
		Importance: 2,
		LastUpdate: "2023-02-01T13:11:01.627",
		Revised: "",
		Currency: "",
		Unit: "",
		Ticker: "MEXICOBC",
		Symbol: "MexicoBC",
	},
	{
		CalendarId: "317667",
		Date: "2023-03-01T15:30:00",
		Country: "Mexico",
		Category: "Manufacturing PMI",
		Event: "S&P Global Manufacturing PMI",
		Reference: "Feb",
		ReferenceDate: "2023-02-28T00:00:00",
		Source: "Markit Economics",
		SourceURL: "https://www.markiteconomics.com",
		Actual: "",
		Previous: "48.9",
		Forecast: "",
		TEForecast: "48",
		URL: "/mexico/manufacturing-pmi",
		DateSpan: "0",
		Importance: 1,
		LastUpdate: "2023-02-01T15:31:37.877",
		Revised: "",
		Currency: "",
		Unit: "",
		Ticker: "MEXICOMANPMI",
		Symbol: "MEXICOMANPMI",
	},
	{
		CalendarId: "317723",
		Date: "2023-03-02T11:00:00",
		Country: "Mexico",
		Category: "Foreign Exchange Reserves",
		Event: "Foreign Exchange Reserves",
		Reference: "Jan",
		ReferenceDate: "2023-01-31T00:00:00",
		Source: "Banco de México",
		SourceURL: "https://www.banxico.org.mx/",
		Actual: "",
		Previous: "$201.1B",
		Forecast: "",
		TEForecast: "$202.0B",
		URL: "/mexico/foreign-exchange-reserves",
		DateSpan: "0",
		Importance: 1,
		LastUpdate: "2023-02-10T15:48:44.39",
		Revised: "",
		Currency: "$",
		Unit: "B",
		Ticker: "MEXICOFOREXCRES",
		Symbol: "MEXICOFOREXCRES",
	},
	{
		CalendarId: "317528",
		Date: "2023-03-02T12:00:00",
		Country: "Mexico",
		Category: "Unemployment Rate",
		Event: "Unemployment Rate",
		Reference: "Jan",
		ReferenceDate: "2023-01-31T00:00:00",
		Source: "Instituto Nacional de Estadística y Geografía (INEGI)",
		SourceURL: "http://www.inegi.org.mx/",
		Actual: "",
		Previous: "2.8%",
		Forecast: "",
		TEForecast: "3.1%",
		URL: "/mexico/unemployment-rate",
		DateSpan: "0",
		Importance: 2,
		LastUpdate: "2023-01-26T12:00:34.317",
		Revised: "",
		Currency: "",
		Unit: "%",
		Ticker: "MXUEUNSA",
		Symbol: "MXUEUNSA",
	},
	{
		CalendarId: "",
		Date: "2023-02-25T16:27:46.1381772+00:00",
		Country:
			"Free accounts have access to the following countries: Mexico, New Zealand, Sweden, Thailand. For more, contact us at support@tradingeconomics.com.",
		Category: "",
		Event: "",
		Reference: "",
		ReferenceDate: null,
		Source: "",
		SourceURL: null,
		Actual: "",
		Previous: "",
		Forecast: "",
		TEForecast: "",
		URL: "",
		DateSpan: "",
		Importance: 1,
		LastUpdate: "2023-02-25T16:27:46.1381772+00:00",
		Revised: "",
		Currency: "",
		Unit: "",
		Ticker: "",
		Symbol: "",
	},
];
